### ISSUE TITLE
Cannot connect to Matek F722-SE

### ISSUE THREAD

**Issue by amusinov** [iNavFlight/inav#4076]
## Current Behavior

My Matek F722-SE with uart GPS & I2C compass works perfect on Betaflight target MATEKF722-SE. Had several flight sessions today, and decided to try INAV leaving all the wiring as is.

I've flashed this board with INAV 2.0.1 target MATEKF722. Uploaded perfectly, rebooted. 
When I am trying to connect via USB and w/o battery, the configurator cannot establish connection without any messages. 
When I power with battery, the buzzer starts to beep. Connecting USB in addition, the configurator still cannot connect, but it looks like the board is constantly rebooting (serial interface ups and downs).

I've tried standalone macos and crome-based configurator v2.

I guess either MATEKF722 firmware doesn't support SE version, or the firmware cannot load due to unpowered I2C compass.

Would appreciate any help. Cheers, Andrew 

- FC Board name and vendor: Matek F722-SE
- INAV version string: 2.0.1

**Comment by teckel12** [comment]
@amusinov There's a F722 SE target for INAV 2.1.  I have the board and the correct target works. I only have development builds of 2.1 but later tonight I may be able to make a stock 2.1 build for you if someone doesn't help first.

In any case, this issue is already resolved.

**Comment by amusinov** [comment]
@teckel12 Thanks for explanation, that is great news. Will be waiting for updates. Btw, where can I find dev-2.1 bin?

I could test it and give a feedback if required.

**Comment by shellixyz** [comment]
@amusinov Here is a dev build (3dc3158ac) of the MATEKF722SE target: 
[inav_2.1.0_MATEKF722SE.hex.zip](https://github.com/iNavFlight/inav/files/2660668/inav_2.1.0_MATEKF722SE.hex.zip)

**Comment by amusinov** [comment]
@shellixyz many thanks!

**Comment by amusinov** [comment]
Hi guys,
have tested 2.1 INAV on MATEKF722SE. Just two issues found.
1) The buzzer doesn't beep at all (wired as and works on BF)
2) RTH mode behaves wierd, flies away and flips.

Decided to put BF back on the quad, but planning to test this firmware again on S800+MATEKF722SE wing soon.

Regards,
Andrew

**Comment by digitalentity** [comment]
I'll look into buzzer issue. As for RTH - it's probably compass-related, however it shouldn't flip. Do you have a CLI dump and BB recording of the failed RTH?

**Comment by amusinov** [comment]
@digitalentity Привет!
The TS100 compass/GPS had been placed 90 CCW, thus, I've set 270 CW and calibrated properly. Sorry, didn't turn BB on, however, have a few videos from my goggles if could help (will drop some links in 10 minutes). I forgot to mention, in both attempts the quad tried to fly away much over 30 metres I've set, looks like on full throttle.

**Comment by amusinov** [comment]
@digitalentity 
https://youtu.be/wZCCkFas3TE

**Comment by teckel12** [comment]
@amusinov Honestly, I'd have to guess that the compass orientation is not correct. Maybe it's flipped?  I can't express enough that you need to be **SURE** the the compass orientation is correct before flying. You're testing in the air very high up, compared to what I test on the bench without props on.

I have a F722 SE but I'm waiting for the frame and ESCs to complete my build. If you don't sort things out, I should be getting the last parts in the next week. I can also look at the buzzer if digitalentity doesn't get to it first.

**Comment by amusinov** [comment]
@teckel12 Hi Tim, good luck with your build.

the compass has been located and declared correctly, I am pretty sure. 
Anyway, I am planning to put F722SE on my S800 fixed wing within next week, and will try to perform testing again.

Btw, guys, are you planning to add Holybro Kakute F7 STM32F745 into the list of supported controllers?

**Comment by shellixyz** [comment]
> Btw, guys, are you planning to add Holybro Kakute F7 STM32F745 into the list of supported controllers?

Already done :wink:. See #3868

**Comment by shellixyz** [comment]
@amusinov If you'd like to test the dev build for the KAKUTEF7 board: [inav_2.1.0_KAKUTEF7.hex.zip](https://github.com/iNavFlight/inav/files/2676704/inav_2.1.0_KAKUTEF7.hex.zip)

Feedback is always welcome

**Comment by teckel12** [comment]
@amusinov Looking into the beeper and LED strip issues today. Once that's cleared up I'll get her in the air and see how RTH works.

**Comment by teckel12** [comment]
@amusinov The following fixes the beeper and the LED strip:

[inav_2.1.0_MATEKF722SE.hex.zip](https://github.com/iNavFlight/inav/files/2706274/inav_2.1.0_MATEKF722SE.hex.zip)

**Comment by teckel12** [comment]
@amusinov I flew the Matek F722SE today with GPS. Position hold and RTH worked perfectly. Tried it several times. Was using the BN-880 GPS correctly orientated.  Also using the development build posted above which fixes both the beeper and LED strip.

I suggest this issue be closed as there's no RTH issue and the other issues are resolved via #4104

**Comment by amusinov** [comment]
@teckel12 I've currently installed inav on Matek F405-ctr on my flying wing. The F722 is currently on my quad with BF. Thank you guys!

**Comment by MartyFufkin** [comment]
@digitalentity, (@teckel12) I think this problem still persists.  I very recently completed a 250mm Quad build with a Matek F722-SE board and Betaflight 3.5 installed flawlessly.  I installed the iNAV firmware from the Matek website (after the versions in the configurator failed with Boot Loops) which offered TWO variants of 2.1.0 at the time... a Dec26 version and a Nov 20 version.  The Nov 20 version resulted in Boot Looping and each time it happened it would be necessary to fix windows with Zadig and then the ImpulseRC tool. It seems that by fluke only, the Dec 26 version installed and Boot Looping stopped.  I fully configured my quad with compass and mag.  I could not get the Sik radio to communicate with the FC on UART3...  so... after much frustration, the RC1 version was released so I hoped this communication would be fixed and installed the RC1 firmware and the Boot Looping started again and it happened with EVERY iNAV 2.1 firmware attempted.  

Also, the ONLY WAY to get the FC recognized by Windows 10 with Zadig and ImpulseRC was to unsolder the 5V power to the GPS and R9-SBUS otherwise ImpulseRC would report and error of: "Unexpected number of devices detected" and FC would NEVER get into DFU and be recognized by windows.

Once a successful DFU is connected, the FC can be installed with iNAV but only to have it Boot Loop before any CLI settings can be examined to troubleshoot OR it can be installed with Betaflight and all of the problems go away.  Betaflight on the board also functions properly for DFU mode with GPS and SBUS and all other Serial devices connected whereas iNAV firmwares required them to be disconnected.

Like @amusinov I'm keeping this F722-SE on Betaflight until hoping the bugs can be resolved.  I'm happy to put iNAV on to help with the troubleshooting.  I also have a DIFF dump from the functioning iNAV 2.1 variant from Dec 26 if that helps.

Thanks.

**Comment by teckel12** [comment]
@MartyFufkin Try the HEX I posted above.  It's slightly before the RC1, but not by much.  I'm running that firmware without any problems.  If it works, I can look at the difference in the target between that firmware and the RC1 firmware you're having a problem with.  I can't test RC1 on my build as I'm in the middle of other testing.  But, I do believe other developers are running RC1 on the F722-SE without issue.

**Comment by MartyFufkin** [comment]
Thanks @teckel12 ...  I downloaded and installed (after unsoldering my GPS) and it installed right away without boot loop... so, I then tried the RC1 and it also worked.  I moved GPS to UART3 and all good.  I think the GPS/MAG was the culprit all along.  Thanks for your help.

**Comment by alfa79** [comment]
Hello,
I have the Matek f722 se and it will not let me connect in inav flight.
makes me:
No configuration received within 10 seconds, communication failed, Serial port successfully opened with ID: 37.
I try to connect with the battery and I have also tried without battery.
can anybody help me?
Thank you.

**Comment by teckel12** [comment]
@alfa79 Not the fault of INAV.  I have the Matek F722SE and it works fine with the configurator.  Sounds like maybe you don't have the correct comm driver installed.  Does the Betaflight configurator communicate correctly?  If you still have a problem, you probably want to open an issue in the configurator repo.  But I can confirm that the Matek F722SE works with INAV and the configurator.

**Comment by alfa79** [comment]
thanks for answering. Yes, in the betaflight it works well and in inav with other controllers it also works. but the matek f722 is, does not connect me. I do not know where the problem may be.

**Comment by MartyFufkin** [comment]
Alfa79, I had same issue... I fixed it by moving the GPS to UART4 instead of UART2.  UART2 seems to cause issues on this board if a GPS is connected when trying to connect.  You may be able to test it by depowering the GPS or unsoldering it from UART2 when trying to connect and flash.  At least this was my problem and how I fixed it.

**Comment by alfa79** [comment]
Thank you MartyFufkin, I have the controller without connecting to anything, only to the esc 4 in 1. The firmware introduces it to me without problems.

**Comment by alfa79** [comment]
Good morning, I have solved it, I have loaded the firmware that put Shellixyz, inav_2.1.0_MATEKF722SE.hex.zip.
It is the only one that works for me.
Thanks to all for the help.
A greeting from Barcelona.

**Comment by bangkokpete** [comment]
Hi, having a similar problem, cannot load OSD characters to FC, stops alleyways at 302/5xx. after that no more video out. reset to BF 4.0.2, install default characters works, back to INAV, start-up message invalid font. AND after that I have constant boot-loop. cannot access the FC under INAV anymore. desoldered all Uarts, no difference. Also copying the diff file into CLI does only shows the last line. anyway to complete reset the FC and the OSD chip ? thanks for your support and your work, already tried 3 F722SE and had similar problems. OmnibusF4pro working perfectly. seems to be a F722SE problem.
Peter

**Comment by damsport11** [comment]
Same problem here. Matek 722 STD, Flash goes OK, then connect does not work:
No configuration received within 10 seconds, communication failed
Betaflight works fine GPS on TX/RX4, TX/RX1 is free

**Comment by MartyFufkin** [comment]
Try unplugging the wire to the GPS (or unsolder one power wire) and try 
again to connect.  This worked for me.  You may have to play with Zadig 
and/or ImpulseRC Driver Fixer to get it working but I did resolve it this way.

**Comment by HoyDAviDJ** [comment]
I was having the exact same problems.  I could not get the Matek F722SE into DFU for anything.  Even plugging in USB with the boot button pressed did nothing.  Once I unplugged the GPS module (Matek M8Q-5883) I was able to put the board into DFU directly from Betaflight like normal and was able to flash without issue.  Once I plugged the GPS back in and reconnected it, Betaflight was no longer able to put the board into DFU.  

I am just glad the issue is not unique to me.

**Comment by DzikuVx** [comment]
@HoyDAviDJ is the GPS was powered from 5V pads, not 4V5 pads, here is the reason: 

https://www.youtube.com/watch?v=W1vLTbvea3A

**Comment by HoyDAviDJ** [comment]
@DzikuVx That wasn't my issue.  My GPS is connected to a 4V5 pad.  I wired the GPS in the same way that it is shown in the F722 SE Manual.  When USB is plugged in, the board boots perfectly fine and connects to Betaflight.  The GPS even gets a 3D fix within about 10 seconds of booting.  

The issue was that when the GPS is connected, Betaflight cannot put the board into DFU with the button on the Configuration Tab or by using commands in the CLI .  The boot button does not put the board into DFU either.  

However, when booting with the GPS unplugged, Betaflight is able to put the board into DFU without issue and flashes normally.  

After I posted my original message I was reading the Betaflight Wiki and found the reason for the problem.  The STM32 group of MCUs look at multiple peripherals, including USB VCP and UARTs, when in Boot Loader mode.  So, if something connected via UART is sending data that looks valid, then the boot loader focuses onto that instead of the USB VCP that it should be.  So, once the GPS is disconnected (at the very least the power to it) then the boot loader focuses onto the correct item, USB VCP, and then Betaflight registers that the device is connected and in DFU.
