### ISSUE TITLE
Taranis X9D Plus X8R XSR Sensor lost.

### ISSUE THREAD

**Issue by DonaldHillNZ** [iNavFlight/inav#4218]
For immediate help, just ask your question on one of the following platforms:

* [Telegram channel](https://t.me/INAVFlight)
* [Facebook group](https://www.facebook.com/groups/INAVOfficial)
* [RC Groups thread](https://www.rcgroups.com/forums/showthread.php?2495732-Cleanflight-iNav-%28navigation-rewrite%29-project)
* [IRC channel](irc://irc.freenode.net/#inavflight)
* [Slack channel](https://publicslack.com/slacks/inavflight/invites/new)

You can also read public documentations or watch video tutorials:

* [Official documentation](https://github.com/iNavFlight/inav/tree/master/docs)
* [Official Wiki](https://github.com/iNavFlight/inav/wiki)
* [Video series by Painless360](https://www.youtube.com/playlist?list=PLYsWjANuAm4qdXEGFSeUhOZ10-H8YTSnH)
* [Video series by Paweł Spychalski](https://www.youtube.com/playlist?list=PLOUQ8o2_nCLloACrA6f1_daCjhqY2x0fB)

**Comment by DonaldHillNZ** [comment]
Can anyone help? I've been struggling with this problem for months now and got to the stage that I put the whole project aside. I've restarted looking at it and have completely disassembled the plane reloaded the latest firmware on the Matek 405 Wing and completely started from scratch, replaced the Rx with another X8R and a XSR, rewired the SPort wires checked everything thoroughly and cannot get rid of this problem. Oh also reloaded the latest firmware on the X8R Rx's. No matter what I do after around 3 or 4 minutes I start getting continual "Sensor lost" messages with the telemetry sensors going for operating to not operating. I've even deleted each sensor one at a time to see if its only one sensor but it happens even if there is only 1 sensor. Ive tried everything I can think of.

**Comment by teckel12** [comment]
@DonaldHillNZ Does this happen on the bench or while flying? Due to heat, I get sensor lost messages in the summer or on the bench. While flying it's never an issue due to air cooling. I believe it's a common problem with FrSky receivers placed too closely to VTx.

**Comment by DonaldHillNZ** [comment]
On the bench Tim but Ive removed everything so no VTX connected and a 
cooling fan playing over the equipment and its definitely not at all 
hot. Everything is not only cool its cold to touch.

------ Original Message ------

**Comment by Nihilistic** [comment]
What version of OpenTX are you running?

**Comment by DonaldHillNZ** [comment]
Ver 2.2.2

**Comment by Nihilistic** [comment]
2.2.3 is out. Might be worth a shot upgrading.

**Comment by DonaldHillNZ** [comment]
great thank you ill give that a shot. Just cant find any other ideas

------ Original Message ------

**Comment by DonaldHillNZ** [comment]
Problem solved by upgrading the firmware on the Taranis to 2.2.3. At least its run for nearly 25 minutes with NO sensor lost.

**Comment by Nihilistic** [comment]
Yay!!

**Comment by Dronitoni** [comment]
here's a workaround from J.B. to that Bug:

https://www.youtube.com/watch?v=d-WSy4odpVE

**Comment by teckel12** [comment]
@Dronitoni That really doesn't fix the problem, just removes the alert, which is an important piece of information to some (typically means you're going out of range).
