### ISSUE TITLE
Airspeed telemetry for CRSF

### ISSUE THREAD

**Issue by MrMap** [iNavFlight/inav#6200]
## Current Behavior
Airspeed not available in OpenTX telemetry page - using TBS crossfire protocol and MATEK F765 Wing with digital Airspeed sensor. Airspeed available in OSD (so the sensor and FC have it)

## Desired Behavior
 I would like airspeed data to be injected into the CRSF telemetry data stream along with the multitude of data already available there 
## Suggested Solution
 I suggest a feature - possibly in collaboration with the TBS dev team - alter the software to include airspeed, when airspeed sensor is available  
 Feature Requests without suggested solutions may not be addressed with the same level of urgency as those that have suggested solutions 

## Who does this impact? Who is this for?
 Who is this for? Airplane users with OpenTX radios / TBS CRSF and a plane with airspeed sensor.  

## Additional context
 Airspeed data into OpenTX telemetry is very useful as it is the primary parameter for flight dynamics. When present it can trigger warnings, add to useful log data and assist (e.g. voice reporting) in keeping desired speed with regard to situation - approach and landing in particular.
As per today my system are on latest stable software releases of OpenTX, TBS tx module, TBS Diversity RX and F765 FC and iNav configurator

**Comment by MrMap** [comment]
I just noticed that Airspeed data gets logged in the Blackbox file - but only the raw values and there are no decoded values.

**Comment by HenHan85** [comment]
when using the inav telemetry widget for OpenTX (Horus), the option to choose airspeed sensor (instead of GPS Speed) in the widget setting is not available. Quite sure because there is no telemetry sensor signal coming throug crsf, providing the airspeed sensor signal.
Would be great to have it included for this purpose

https://github.com/iNavFlight/OpenTX-Telemetry-Widget

**Comment by alexgalstyan** [comment]
Hello,
Is this issue was resolved ?

**Comment by pnduffy** [comment]
I tried getting airspeed telemetry with CRSF protocol, over ExpressLRS, but no airspeed selection is available in the LUA script.  I didn't see if this was closed for a solution or not.  Any comments?

**Comment by Enggmaug** [comment]
Hello, 

I'm looking for the very same thing : Pitot data through ExpressLRS CRSF telemetry.

If I understand [this page](https://github.com/iNavFlight/inav/issues/3886) : it should be already possible... But I still don't see how.

**Comment by uwe-air** [comment]
Hi same here. PLEASE try to get this done. So i can get an stallwarning working .

**Comment by pnduffy** [comment]
I compiled a custom version of INav to get airspeed.  Not sure if it's in the mainline yet.

**Comment by MrMap** [comment]
> > Hi same here. PLEASE try to get this done. So i can get an stallwarning working .
> 
> Airspeed shouldn't be used for stall warnings. Stalls can still happen at higher airspeeds. Stalls are caused by separation of airflow from the wing.

It is correct that stall speed (Vs) is not a constant but a function of factors, e.g. weight, configuration and g-load.
However, airspeed is the only speed relevant to flight dynamics, hence including it in the CRSF telemetry protocol is desirable and frankly, surprising that it did not make it´s way in from the beginning.

Though stall speed can vary, using airspeed as a low speed warning is a great idea. This warning indicates that you are flying with low margin to stall speed promt the pilot to take proper action. Typical situation is final approach with an aircraft. On my Avanti S I have my radio read the airspeed repeating every few seconds (using FrSky RX and FrSky series sensor.

I even made a setup in Edge TX adapting the gyro gain to the airspeed, hence optimizing the gyro performance all over the speed range.
Airspeed is not only useful, it´s central.

**Comment by sensei-hacker** [comment]
> It is correct that stall speed (Vs) is not a constant but a function of factors, e.g. weight, configuration and g-load. However, airspeed is the only speed relevant to flight dynamics, hence including it in the CRSF telemetry protocol is desirable


 Yes, airspeed is an important parameter if you were trained as / like a full size pilot.

It is ALSO important to understand that you can stall at any speed. Someone who thinks the plane won't stall until a particular speed is also a person whose planes keep inexplicably dropping out of the sky during base turn.

**Comment by OptimusTi** [comment]
Airspeed is not in the CRSF protocol. Please reach out to TBS to add it.

**Comment by MrMap** [comment]
> > It is correct that stall speed (Vs) is not a constant but a function of factors, e.g. weight, configuration and g-load. However, airspeed is the only speed relevant to flight dynamics, hence including it in the CRSF telemetry protocol is desirable
> 
> Yes, airspeed is an important parameter if you were trained as / like a full size pilot.
> 
> It is ALSO important to understand that you can stall at any speed. Someone who thinks the plane won't stall until a particular speed is also a person whose planes keep inexplicably dropping out of the sky during base turn.

Yes, good point - but not a reason against having airspeed in the CRSF telemetry protocol.

On a side not, AOA - Angle Of Attack - is a very useful parameter to monitor while staying out of stall trouble.
Unfortunately I have never seen such a sensor for RC use. Maybe to mechanically messy and expensive to translate into RC plane size. But it would be cool.

**Comment by pnduffy** [comment]
GA planes have color-coded airspeed indicators showing stall region. It's not an absolute indicator of stall, but during takeoff and landings where the wings are typically level and the angle of attack is not excessive, it's a good indicator. AOA can be detected by the accelerometer if it's calibrated correctly.

**Comment by sensei-hacker** [comment]
> Unfortunately I have never seen such a sensor for RC use

I have designed a couple. Both an AoA indicator and a direct stall sensor such as you often see on light aircraft. I can send you the STL if you would like to try it out.

**Comment by sensei-hacker** [comment]
> Unfortunately I have never seen such a sensor for RC use.

I've designed a couple. Both AoA and an actual stall sensor. I can send you the STL if you would like to try it out. This style often seem on GA aircraft is probably the simplest and most reliable.

![main-qimg-b58275a285c34bc119c06df1037783c4-lq (2)](https://github.com/iNavFlight/inav/assets/1971284/456b295d-871c-4032-b4e4-45467614070e)


It's just a toggle switch, which flips up when the stagnation point falls below the set point (meaning the AoA is higher than the selected setting).

For RC use, low friction is required, so I designed it with a cheap Hall sensor for frictionless switching.  The same design turned backwards is an AoA sensor.

**Comment by uwe-air** [comment]
Hi i got my ATPL 20 Years ago. We use in the  Aircraft for the  Stallcomputer a mix of :AOA, Speed , flap-setting, Bankangle , Altitude......20millon dots ........etc . Way to complicated to implement this in a hobby modell plane. BUT for what doe we use it in our model?? I dont care if i am high enought to get a stall in a turn . But when i fly nearly straight for landing than the speed i well enogh to use in a model. ( ps the stallspeed dont care about the waight !!!! Its a matter of (non) turbulent airflow on your wing .)

@ sensei-hacker :brilliant don those we had in the fligtshool on the most of the light Aircrafts

**Comment by james-au** [comment]
We definitely need airspeed telemetry to set our min/max alarms.  Every scalar telemetry value should have user settable alarms.

There are also "overspeed" conditions (like during a dive) as oscillations can snap a wing quite quickly (been there done that).

On the low end of speed, it's not too uncommon to get distracted with the FPV views and other aspects of flight to forget about a low throttle position.  Especially as digital FPV video does _not_ include audio transmission so the pilot can't even audibly monitor motor throttle as we did with analog FPV.  A "low air speed" alert can save FPV lives!

**Comment by james-au** [comment]
> I compiled a custom version of INav to get airspeed. Not sure if it's in the mainline yet.

Excellent.  Can you send me a link to the branch/pull request/diff for this change?
